### PR TITLE
pin gdal 2.1.x

### PR DESCRIPTION
**Pull request by ocefpaf**
Unfortunately `fiona` is not compatible with `gdal 2.2.*` yet, so we need to pin everything to `2.1.*` is we want to install them along side with `fiona`. Note that installing the previous build number with latest `gdal` is still possible when not installing `fiona`.

I also update the `boost` pin to `1.64.*`.

@gillins does it make sense to change the dependency here to `libgdal` instead of `gdal`? Or do you need the python bindings for this package?

### CODE REVIEW

**Comment by danclewley** [comment]
> does it make sense to change the dependency here to libgdal instead of gdal? Or do you need the python bindings for this package?

The python bindings are needed so better to keep as `gdal`

**Comment by ocefpaf** [comment]
> The python bindings are needed so better to keep as `gdal`

Thanks for the clarification @danclewley!

**Comment by ocefpaf** [comment]
I guess that `conda-inspect` is taking to long :unamused: I will try commenting it out.

```
Removing test files
84 TESTS COMPLETED - 0 FAILURES LISTED BELOW:
+ conda inspect linkages -p /feedstock_root/build_artefacts/rsgislib_1500577686313/_t_env rsgislib

command ./ci_support/run_docker_build.sh took more than 10 minutes since last output
```

**Comment by gillins** [comment]
Sorry @ocefpaf I forgot all about this PR. Do you want to re-sync it, and then I'll merge it?

**Comment by ocefpaf** [comment]
No problem. I used the GitHub web interface. Hopefully everything is alright.

**Comment by gillins** [comment]
Does the build number need to be updated also?

**Comment by ocefpaf** [comment]
> Does the build number need to be updated also?

Done!

**Pull request merged**
