### PR TITLE
Updated to version 3.5.7

### PR DESCRIPTION
**Pull request by petebunting**
Keeping update, with the latest release of RSGISLib

### CODE REVIEW

**Comment by petebunting** [comment]
Hi @gillins @danclewley 

I get an error from the RSGISLib compilation from GDAL associated with GLIBCXX

 "libgdal.so: undefined reference to `std::string::back()@GLIBCXX_3.4.15" 

Any ideas how to resolve?

Cheers, Pete

**Comment by gillins** [comment]
@petebunting this might be the same issue discussed here: https://github.com/conda-forge/libgdal-feedstock/pull/42#issuecomment-389694644.

@ocefpaf Is this a simple matter of adding `libstdcxx-ng` to the requirements on Linux?

**Comment by petebunting** [comment]
Hi @gillins, 

That does seem to have solved the issue and working now. 

Cheers, Pete

**Comment by ocefpaf** [comment]
> @ocefpaf Is this a simple matter of adding `libstdcxx-ng` to the requirements on Linux?

I guess that the right thing to do is to add that to `libgdal`. I did not really wanted to do that b/c once we move the recipes to the new format and the new compilers that will be unnecessary. However, new releases of packages that depend on `libgdal` and the slow move to the new compilers I guess we don't have a choice.

I'll do that soon and then we can remove `libstdcxx-ng` from here.

**Pull request merged**
