### PR TITLE
Update to build latest release of rsgislib

### PR DESCRIPTION
**Pull request by petebunting**
I've updated the build so it should build using the updated cmake build scripts which build out of the source path.

### CODE REVIEW

**Comment by petebunting** [comment]
The error is:
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - boost-cpp=1.68.0
  - cgal -> boost-cpp[version='>=1.67.0,<1.67.1.0a0']

@gillins do you know what we need to do to fix this?

**Comment by gillins** [comment]
Hi Pete. We have been left behind by the [compiler migration](https://conda-forge.org/docs/news_announce.html) ... `rsgislib` hasn't been migrated because CGAL appears to have issues with the latest compilers (see https://github.com/conda-forge/cgal-feedstock/pull/41). I don't think we will be able to rebuild `rsgislib` (or get a usable new environment with it in) until this is complete.

BTW I suspect there will be problems with `rsgislib` with the new compilers on Linux as they now default to C++17 and the [Dynamic exception specification](https://en.cppreference.com/w/cpp/language/except_spec) has been removed and results in an error. I've already updated `kealib` - took quite a while.

**Comment by petebunting** [comment]
Thanks Sam. 

OK. I’ll take a look at sorting out the exception statements. I had it on the list of things to sort out for a ‘version 4.X’ rsgislib which has a few other more significant changes. I guess it’ll be a little while before I get chance to do that work mind.

Cheers, Pete

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
