### PR TITLE
pin geos to 3.6.2

### PR DESCRIPTION
**Pull request by ocefpaf**
Update some pinnings.

### CODE REVIEW

**Comment by gillins** [comment]
@danclewley @petebunting are you guys aware of [this error](https://travis-ci.org/conda-forge/rsgislib-feedstock/jobs/298500095#L972) when building against the latest `geos`?

**Comment by petebunting** [comment]
Hi Sam / @gillins <https://github.com/gillins>, 

No, I wasn’t aware of that… Looks like there has been some redacting of GEOS maybe. I’ll try and take a look at it this week. 

Cheers, Pete

**Comment by petebunting** [comment]
Hi @gillins <https://github.com/gillins> and @danclewley <https://github.com/danclewley>,

Just to confirm I have fixed this issue in the development branch. @danclewley <https://github.com/danclewley> I guess we should decide whether it is worth creating a new release soon with this fix… 

Cheers, Pete

**Comment by ocefpaf** [comment]
I add one extra commit to make this ready for merging when the `geos` issue is sorted out.

**Comment by gillins** [comment]
@danclewley @petebunting any luck doing a new release?

**Comment by danclewley** [comment]
We've now created a new release. Is it easier to just add to this PR?:

Version is: 3.4.9
Checksum is: `a271aee61395166542f3283fe899eff317ffb782f59ca90da0f008a203ebe5f3`

**Comment by ocefpaf** [comment]
> We've now created a new release. Is it easier to just add to this PR?

Sure, but we got some new failures now I guess :smile:

**Comment by danclewley** [comment]
@petebunting, any idea why this isn't building? Looks like it is getting to about 4 % then failing.

**Comment by gillins** [comment]
Sorry, only just got to this. @ocefpaf any ideas why this is pulling in `libgdal` from defaults? Also, seems to be compiling in C++11 mode, not sure this is relevant, but I thought we weren't doing this yet... Seems the errors may well be related to ABI mismatch.

**Comment by danclewley** [comment]
Is it pulling in `libgdal` from defaults because `hdf5` is pinned to `1.8.18|1.8.18.*` I think it needs to change to `hdf5 1.10.1|1.10.1.*`.

**Comment by danclewley** [comment]
@gillins, any idea why the travis build is still going or how to restart?

**Comment by gillins** [comment]
See https://github.com/conda-forge/libgdal-feedstock/issues/30#issuecomment-351384852. Hopefully it will finish soon, I'll keep an eye on it. BTW closing then opening a PR will cause the CIs to restart.

**Comment by gillins** [comment]
Yay!

**Comment by ocefpaf** [comment]
:tada:

**Pull request merged**
