### PR TITLE
Pin boost 1.64

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by gillins** [comment]
Thanks @jschueller

**Comment by gillins** [comment]
@ocefpaf I'm getting the following failure with CircleCI and I'm guessing the other CI's are failing too since no new packages have been uploaded. Any ideas?

```
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []
Using Anaconda API: https://api.anaconda.org
Using Anaconda API: https://api.anaconda.org
[ERROR] 
Traceback (most recent call last):
  File "/opt/conda/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/scripts/cli.py", line 88, in main
    description=__doc__, version=version)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/commands/upload.py", line 242, in main
    args=args)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/commands/upload.py", line 199, in upload_package
    callback=upload_print_callback(args))
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/__init__.py", line 506, in upload
    self._check_response(res)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/__init__.py", line 216, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.Unauthorized: ('Authorization token is no longer valid', 401)
Traceback (most recent call last):
  File "/opt/conda/bin/upload_or_check_non_existence", line 122, in <module>
    main()
  File "/opt/conda/bin/upload_or_check_non_existence", line 111, in main
    upload(cli, meta, owner, channel)
  File "/opt/conda/bin/upload_or_check_non_existence", line 62, in upload
    env=os.environ)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', 'binstar.token', 'upload', '/feedstock_root/build_artefacts/linux-64/rsgislib-3.2.0-py27_3.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.

./ci_support/run_docker_build.sh returned exit code 1
```

**Comment by jschueller** [comment]
packages must be readded: https://github.com/conda-forge/conda-forge.github.io/issues/426

**Comment by ocefpaf** [comment]
@gillins we had an issue with the anaconda upload token. The short term solution is to re-add the recipe like @jschueller mentioned. That will refresh the token without changing anything else from the feedstock. We are looking into a long term solution.

**Comment by jschueller** [comment]
https://github.com/conda-forge/staged-recipes/pull/3698

**Comment by ocefpaf** [comment]
Thanks @jschueller!

**Pull request merged**
