### PR TITLE
Update to version 3.6.14

### PR DESCRIPTION
**Pull request by gillins**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #17 and #16

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@petebunting, @danclewley I've managed to get this passing and built. Turns out that they have relaxed the C++17 requirements and it now passes on Linux but with a bunch of warnings. Let me know if there are any problems.

There were a few changes needed to make it build - I'll push these into bitbucket. BTW best to use `hg archive` when creating a tarball - seems some [rubbish](https://ci.appveyor.com/project/conda-forge/rsgislib-feedstock/builds/23324554/job/mqq888f3f0r14wvh#L47358) made it in to this one.

I had to skip the running the test suite on Windows - seemed to randomly crash. Not sure what that is about.

I'll have a look at `spdlib` when I get a chance.

cc: @petescarth

**Comment by petebunting** [comment]
HI Sam, 

That is great, that you very much for your efforts here - it is really appreciated. 

I’ve quickly tested on the Mac and it seems to be working OK. We should have the next release of RSGISLib available shortly but I’m planning to look at C++17 support in April. 

Cheers, Pete

**Comment by danclewley** [comment]
Thanks for doing this Sam. I've tested on Linux and Windows both with Python 3.7. For windows it didn't work straight away, I needed to run `conda update --all` after.

**Pull request merged**
