### PR TITLE
Update for 5.0.1

### PR DESCRIPTION
**Pull request by petebunting**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
```
-- installing Python libs to D:/bld/rsgislib_1643066936389/_h_env/Library/Lib/site-packages
```

Shouldn't have the 'Library' bit in there. I see that you pass `Python_ROOT_DIR=%PREFIX%` which should get it to do the right thing, but then the code in https://github.com/remotesensinginfo/rsgislib/blob/main/python/CMakeLists.txt#L14-L23 does the wrong thing (sorry, this was probably me). I think this was doing the right thing for `modules` but not for conda under Windows...

Not sure the best way forward but this could be simplified quite a bit, but this might break it for `modules` - maybe there needs to be another switch?

**Comment by petebunting** [comment]
Thanks @gillins, 

I've had a bit of a look at this and have to say my lack of knowledge of Windows is a bit of a blocker here. Looking through the logs it seems 'Library' is within most of the install paths but without having a system to have a look at I am finding it a bit difficult to try and work out what is going on here and therefore where to start fixing this. 

In terms of the way forward, if you can see a fix and are happy to have a look then great but otherwise I might drop windows builds from conda-forge for the time being and try to source a Windows machine I can have a play with to debug what is going on here.

**Comment by gillins** [comment]
@petebunting for now, I reckon change https://github.com/remotesensinginfo/rsgislib/blob/main/python/CMakeLists.txt#L16 to:
```
if(NOT MSVC AND NOT CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
```
So we don't do anything fancy on Windows at all for now. We may have to rethink how this all works in future...

See how that goes. If it still fails dropping Windows sounds like a good plan and we can work out a solution later.

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by petebunting** [comment]
Thanks @gillins, 

Trying that now. See what happens.

**Comment by petebunting** [comment]
@gillins, looks like your fix has sorted out the installation issue. :) Thank you!

Got a few test issues to look at on windows though but suspect they are largely simple fixes... Something for tomorrow.

**Comment by gillins** [comment]
Yeah looks like you are trying to run python scripts with `subprocess` without passing `sys.executable` first (Windows doesn't have a `#!` mechanism). Or use the functions in `osgeo.utils`.... Let me know if you need any help.

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by petebunting** [comment]
@gillins - thank you for your help. All seems to be working OK now so will merge this one and then sort out the other pull requests for py3.10 etc.

**Comment by gillins** [comment]
Well done @petebunting !

**Pull request merged**
