### PR TITLE
Update to use kealib 1.4.9 and GSL 2.4

### PR DESCRIPTION
**Pull request by petebunting**

### CODE REVIEW

**Comment by gillins** [comment]
Hi @petebunting I meant to talk to you about all this stuff. I think we need a plan for moving to the "new format" and new compilers which will make life easier but will require a bit of work... I guess we wait for the automatic PR to convert to the new format and work it out from there.

Kealib 1.4.9 only works with the new format recipes where C++11 seems to be the default. I had to patch kealib 1.4.9 to remove the `-std=c++98` flag which breaks linking against C++11 code. I see there is the same thing in `rsgislib`....

I've also discovered `kealib` wasn't building at all in C++17 mode - see my `cxx17` branch - `throw` is no longer accepted as part of a function definition. I'm not sure if you want to consider doing the same for `rsgislib`?

Anyway, I'm thinking of doing (yet another) `kealib` release to fix the above 2 things soon if you are ok with that.

**Comment by gillins** [comment]
BTW the default conda-forge pinning for `gsl` is still 2.2.* (https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L254) ...

**Comment by isuruf** [comment]
Please use PRs from a fork in the future.

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
