### PR TITLE
Update boost pin

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by danclewley** [comment]
Is there a reason re-rendering with conda-smithy removed `CONDA_PY=36` from the build matrix?

**Comment by gillins** [comment]
Weird. Only did that for OSX... ping @ocefpaf

**Comment by ocefpaf** [comment]
> Weird. Only did that for OSX... ping @ocefpaf

Probably some package is missing and preventing the correct re-rendering. Let me check...

**Comment by ocefpaf** [comment]
It seems that it was just the Travis-CI backlog holding some of the dependencies. Re-rendering again should fix it.

@conda-forge-admin, please rerender

**Comment by gillins** [comment]
Thanks @ocefpaf that was it!

@jschueller any idea why the `boost` libs have changed their names on Windows? They no longer have the MSVC version etc in the name. I'll try putting together a patch to work around it.

**Pull request merged**
