### PR TITLE
Update to release 4.1 and download release from github where code is …

### PR DESCRIPTION
**Pull request by petebunting**
…now hosted.

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
Hi @petebunting great that there will be a new version!

BTW I *think* that the recommended way to pin versions these days is to create a `conda_build_config.yaml` in the recipe dir with something like this (not in `meta.yaml`), then re-render:
```
geos:
  - 3.7.2
cgal-cpp:
  - 4.14
```
I'm not much of an expert though...

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by petebunting** [comment]
@conda-forge-admin, please rerender

**Comment by petebunting** [comment]
> Hi @petebunting great that there will be a new version!
> 
> BTW I _think_ that the recommended way to pin versions these days is to create a `conda_build_config.yaml` in the recipe dir with something like this (not in `meta.yaml`), then re-render:
> 
> ```
> geos:
>   - 3.7.2
> cgal-cpp:
>   - 4.14
> ```
> 
> I'm not much of an expert though...

Thanks @gillins (hope all is well with you guys in these rather strange times!), tried that and it then got in a mess saying it couldn't find geos 3.7.2 as it was using gdal 3.0.4 (rather than 3.0.1) which is built against geos 3.8.1. I used the geos c++ api in rsgislib and that is the problem here. 

They've since recommended that the geos c api is used and the c++ is not as the interface won't be stable. Much of the code which is using geos is not being used or to be honest, really maintained, so I think the answer here is to remove geos as a direct rsgislib dependency and where needed use through ogr. I'll try and get this building on all the platforms now - still have an odd windows error where it builds but then cannot import rsgislib when it runs the tests. I'll then look at removing direct imports of geos from rsgislib over the next week or so.

The issue with cgal seems to be related to the compile version (i think) as the error is related to the stl. I'll put pulled this over from my dev builds on my local machine so now it's re-rendered this might have been solved and I might not need to pin the version - hopefully!

**Comment by petebunting** [comment]
@gillins and @danclewley, it now builds for all the python versions and platforms. However, I've had to pin geos and cgal versions. I wasn't able to use conda_build_config.yaml as it didn't pull appropriate versions. 

Going forward, I think I will remove geos as a dependency to rsgislib. CGAL, I haven't been able to work out all the errors with the latest version. The original error was being unable to find std::enable_if_t, which was introduced in c++14. I have, therefore, moved to use c++14 but now the most recent version of cgal gives an error about being unable the library. 

Are you happy if I merge this pull request? I'll then work on removing geos for the next release hopefully in the next month or so as until this is done it won't compile against the most up to date version of GDAL. Hopefully, I can also work out what is going on with CGAL as well.

**Comment by gillins** [comment]
Sounds good to me!

**Pull request merged**
